// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRufv0iF2ov2zY24OLT4uFZntQaFIJpA',
    appId: '1:862776567455:web:6984a6d1db74a9feb9a4aa',
    messagingSenderId: '862776567455',
    projectId: 'tripplan-de193',
    authDomain: 'tripplan-de193.firebaseapp.com',
    storageBucket: 'tripplan-de193.appspot.com',
    measurementId: 'G-R7H6JD6MJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1HgbhWRlZoszG_qgpYJ86_tHrYcHhRIw',
    appId: '1:862776567455:android:fb7c6f33bce23db1b9a4aa',
    messagingSenderId: '862776567455',
    projectId: 'tripplan-de193',
    storageBucket: 'tripplan-de193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWP4ycp1g2yOOUV5GUCqitf5V24uxJiu0',
    appId: '1:862776567455:ios:9011b644924eb3d0b9a4aa',
    messagingSenderId: '862776567455',
    projectId: 'tripplan-de193',
    storageBucket: 'tripplan-de193.appspot.com',
    iosBundleId: 'com.example.tripPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWP4ycp1g2yOOUV5GUCqitf5V24uxJiu0',
    appId: '1:862776567455:ios:9011b644924eb3d0b9a4aa',
    messagingSenderId: '862776567455',
    projectId: 'tripplan-de193',
    storageBucket: 'tripplan-de193.appspot.com',
    iosBundleId: 'com.example.tripPlan',
  );

}